// <auto-generated />
using System;
using InvoiceFlowAI.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InvoiceFlowAI.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(InvoiceFlowDbContext))]
    partial class InvoiceFlowDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:JsonTypeColumn", "TEXT");

            modelBuilder.Entity("InvoiceFlowAI.Infrastructure.Persistence.Entities.ArchivedArtifactRow", b =>
                {
                    b.Property<string>("ArtifactId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("AlreadyExisted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("CommittedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("FinalFilePath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProcessingRevision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceFileName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("TempFilePath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.HasKey("ArtifactId");

                    b.HasIndex("RunId", "DocumentId", "ProcessingRevision", "Role", "ContentHash")
                        .IsUnique();

                    b.ToTable("ArchivedArtifacts", (string)null);
                });

            modelBuilder.Entity("InvoiceFlowAI.Infrastructure.Persistence.Entities.AuditEventRow", b =>
                {
                    b.Property<string>("AuditEventId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentId")
                        .HasColumnType("TEXT");

                    b.Property<long>("EventSequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("NodeId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProcessingRevision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("AuditEventId");

                    b.HasIndex("RunId", "EventSequence")
                        .IsUnique();

                    b.HasIndex("DocumentId", "ProcessingRevision", "EventType");

                    b.ToTable("AuditEvents", (string)null);
                });

            modelBuilder.Entity("InvoiceFlowAI.Infrastructure.Persistence.Entities.DocumentProcessingRow", b =>
                {
                    b.Property<string>("DocumentId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProcessingRevision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArtifactPath")
                        .HasColumnType("TEXT");

                    b.Property<int>("Attempt")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultJson")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Retryable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("TraceJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("DocumentId", "ProcessingRevision");

                    b.HasIndex("RunId", "Sequence")
                        .IsUnique();

                    b.ToTable("DocumentProcessing", (string)null);
                });

            modelBuilder.Entity("InvoiceFlowAI.Infrastructure.Persistence.Entities.DocumentSourceRow", b =>
                {
                    b.Property<string>("DocumentId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("MimeType")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderGroupKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceFileName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceLocator")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceMessageUid")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("DocumentId");

                    b.HasIndex("ContentHash");

                    b.ToTable("Documents", (string)null);
                });

            modelBuilder.Entity("InvoiceFlowAI.Infrastructure.Persistence.Entities.InvoiceItemRow", b =>
                {
                    b.Property<string>("InvoiceItemId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<string>("InvoiceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Quantity")
                        .HasColumnType("TEXT");

                    b.Property<string>("Specification")
                        .HasColumnType("TEXT");

                    b.Property<string>("TaxAmount")
                        .HasColumnType("TEXT");

                    b.Property<string>("TaxRate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .HasColumnType("TEXT");

                    b.Property<string>("UnitPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("InvoiceItemId");

                    b.HasIndex("InvoiceId", "Ordinal")
                        .IsUnique()
                        .HasDatabaseName("IX_InvoiceItems_Ordinal");

                    b.ToTable("InvoiceItems", (string)null);
                });

            modelBuilder.Entity("InvoiceFlowAI.Infrastructure.Persistence.Entities.InvoiceRow", b =>
                {
                    b.Property<string>("InvoiceId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Amount")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ArchiveState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("Confidence")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("DuplicateKey")
                        .HasColumnType("TEXT");

                    b.Property<int>("Flags")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InvoiceCode")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("InvoiceDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("InvoiceNumber")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProcessingRevision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Purchaser")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Seller")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("TaxAmount")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TotalAmount")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("InvoiceId");

                    b.HasIndex("DuplicateKey");

                    b.HasIndex("InvoiceNumber", "Seller", "InvoiceDate", "TotalAmount");

                    b.ToTable("Invoices", (string)null);
                });

            modelBuilder.Entity("InvoiceFlowAI.Infrastructure.Persistence.Entities.LegacyImportStateRow", b =>
                {
                    b.Property<string>("ImportId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("ImportVersion")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("ImportedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("SecretReentryRequired")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("ImportId");

                    b.ToTable("LegacyImportState", (string)null);
                });

            modelBuilder.Entity("InvoiceFlowAI.Infrastructure.Persistence.Entities.LegacyArchiveInventoryRow", b =>
                {
                    b.Property<string>("InventoryId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("RootKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalRelativePath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentRelativePath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceFileName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReviewRunId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("InventoryId");

                    b.HasIndex("RootKey", "OriginalRelativePath", "ContentHash")
                        .IsUnique();

                    b.HasIndex("RootKey", "State");

                    b.ToTable("LegacyArchiveInventory", (string)null);
                });

            modelBuilder.Entity("InvoiceFlowAI.Infrastructure.Persistence.Entities.MailboxAccountRow", b =>
                {
                    b.Property<string>("AccountId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CredentialName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultMailbox")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImapHost")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("ImapPort")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("UseTls")
                        .HasColumnType("INTEGER");

                    b.HasKey("AccountId");

                    b.ToTable("MailboxAccounts", (string)null);
                });

            modelBuilder.Entity("InvoiceFlowAI.Infrastructure.Persistence.Entities.MailboxCursorRow", b =>
                {
                    b.Property<string>("AccountId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Mailbox")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("CursorRevision")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastCompletedUid")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UidValidity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("AccountId", "Mailbox");

                    b.ToTable("MailboxCursors", (string)null);
                });

            modelBuilder.Entity("InvoiceFlowAI.Infrastructure.Persistence.Entities.ManualReviewItemRow", b =>
                {
                    b.Property<string>("ReviewId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentResultJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentRevision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DocumentId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProcessingRevision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ResolvedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResolvedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("ReviewId");

                    b.ToTable("ManualReviewItems", (string)null);
                });

            modelBuilder.Entity("InvoiceFlowAI.Infrastructure.Persistence.Entities.PairingRow", b =>
                {
                    b.Property<string>("PairingId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanionDocumentIdsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanionProcessingRevisionsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("InvoiceDocumentId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("InvoiceProcessingRevision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Score")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("PairingId");

                    b.HasIndex("RunId", "InvoiceDocumentId", "InvoiceProcessingRevision")
                        .IsUnique();

                    b.ToTable("Pairings", (string)null);
                });

            modelBuilder.Entity("InvoiceFlowAI.Infrastructure.Persistence.Entities.RuleSetRow", b =>
                {
                    b.Property<string>("RuleSetId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AstFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NormalizedAstJson")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentVersion")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RollbackFromVersion")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RollbackTargetVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RuleSetId", "Version");

                    b.HasIndex("AstFingerprint");

                    b.HasIndex("SourceFingerprint");

                    b.ToTable("RuleSets", (string)null);
                });

            modelBuilder.Entity("InvoiceFlowAI.Infrastructure.Persistence.Entities.RunCheckpointRow", b =>
                {
                    b.Property<string>("RunId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("NodeId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("CheckpointRevision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InputCursorJson")
                        .HasColumnType("TEXT");

                    b.Property<long>("LastCommittedSequence")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OutputCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("RunId", "NodeId");

                    b.HasIndex("RunId", "Stage", "LastCommittedSequence");

                    b.ToTable("RunCheckpoints", (string)null);
                });

            modelBuilder.Entity("InvoiceFlowAI.Infrastructure.Persistence.Entities.RunEventRow", b =>
                {
                    b.Property<string>("RunId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("EventSequence")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("EmittedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RunId", "EventSequence");

                    b.HasIndex("RunId", "ExpiresAtUtc");

                    b.ToTable("RunEvents", (string)null);
                });

            modelBuilder.Entity("InvoiceFlowAI.Infrastructure.Persistence.Entities.RunRow", b =>
                {
                    b.Property<string>("RunId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int?>("AccountRevision")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("CancellationRequestedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigurationFingerprint")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DateFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DateToExclusive")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("EndedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("LastEventSequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mailbox")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputRoot")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryFailureJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecipeVersion")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("RuleSetId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int?>("RuleSetVersion")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SettingsRevision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("SummaryJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("TerminalReasonCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("RunId");

                    b.HasIndex("ConfigurationFingerprint");

                    b.HasIndex("Stage");

                    b.HasIndex("State");

                    b.ToTable("Runs", (string)null);
                });

            modelBuilder.Entity("InvoiceFlowAI.Infrastructure.Persistence.Entities.UserSettingsRow", b =>
                {
                    b.Property<string>("SettingsId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("AllowVisionFallback")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConfigurationFingerprint")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentAccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultMailbox")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastOutputDirectory")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("MailboxFiltersJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("PipelineOptionsJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RuleSetId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("RuleSetVersion")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("SettingsId");

                    b.ToTable("UserSettings", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
